services:
  comfyui:
    build:
      context: .
      dockerfile: amd.dockerfile
    volumes:
      - ./ComfyUI:/app/ComfyUI
    ports:
      - "7680:${PORT:-7680}"
    devices:
      - "/dev/dri:/dev/dri"
      ## For AMD GPU
      - "/dev/kfd:/dev/kfd"
