services:
  main:
    build:
      context: .
      dockerfile: amd.dockerfile
    volumes:
      - ./ComfyUI:/app/ComfyUI
    ports:
      - "7860:${PORT:-7860}"
    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/kfd:/dev/kfd"
    restart: unless-stopped
