services:
  comfyui:
    build: .
    ports:
      - "7680:${PORT:-7680}"
    volumes:
      - ./models:/app/ComfyUI/models
      - ./input:/app/ComfyUI/input
      - ./output:/app/ComfyUI/output
      - ./custom_nodes:/app/ComfyUI/custom_nodes
      - ./web:/app/ComfyUI/web
    deploy:
       resources:
         reservations:
           devices:
             - driver: nvidia
               count: all
               capabilities: [gpu]
    devices:
      - "/dev/dri:/dev/dri"
