version: "3"
name: comfyui
services:
  main:
    build: .
    ports:
      - "7680:${PORT:-7680}"
    volumes:
      - ./ComfyUI:/app/ComfyUI
    deploy:
       resources:
         reservations:
           devices:
             - driver: nvidia
               count: all
               capabilities: [gpu]
    devices:
      - "/dev/dri:/dev/dri"
    restart: unless-stopped
