services:
  main:
    build: 
      context: .
      dockerfile: cpu.Dockerfile
    container_name: comfyui-main
    environment:
      - COMFYUI_PATH=${COMFYUI_PATH:-/app/ComfyUI}
    volumes:
      - ./ComfyUI:/app/ComfyUI
    ports:
      - "7860:${PORT:-7860}"
    devices:
      - "/dev/dri:/dev/dri"
    restart: unless-stopped
  copyparty:
    image: copyparty/ac:latest
    container_name: comfyui-copyparty
    ports:
      - 3923:3923
    volumes:
      - ./cfg:/cfg
      - ./ComfyUI:/w
    restart: unless-stopped

    stop_grace_period: 15s  # thumbnailer is allowed to continue finishing up for 10s after the shutdown signal
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q 127.0.0.1:3923/?reset"]
      interval: 1m
      timeout: 2s
      retries: 5
      start_period: 15s

