version: "3"
name: comfyui
services:
  main:
    build: 
      context: .
      dockerfile: cpu.Dockerfile
    volumes:
      - ./ComfyUI:/app/ComfyUI
    ports:
      - "7680:${PORT:-7680}"
    devices:
      - "/dev/dri:/dev/dri"
    restart: unless-stopped
