services:
  main:
    build: 
      context: .
      dockerfile: cpu.Dockerfile
    volumes:
      - ./ComfyUI:/app/ComfyUI
    ports:
      - "7860:${PORT:-7860}"
    devices:
      - "/dev/dri:/dev/dri"
    restart: unless-stopped
