services:
  main:
    build:
      context: .
      dockerfile: Dockerfile.amd
    container_name: comfyui-main
    environment:
      - COMFYUI_PATH=${COMFYUI_PATH:-/app/ComfyUI}
      - DOWNLOAD_FLUX=0
    volumes:
      - ./ComfyUI:/app/ComfyUI
    ports:
      - "7860:${PORT:-7860}"
    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/kfd:/dev/kfd"
    restart: unless-stopped
